services:
  - type: web
    name: enhanced-timetable-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn enhanced_timetable_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: timetable-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: timetable-db
    databaseName: enhanced_timetable_system
    user: timetable_user
